definitions:
  main.appInfo:
    properties:
      running:
        type: boolean
      time:
        $ref: '#/definitions/main.timeInfo'
    type: object
  main.timeInfo:
    properties:
      now:
        type: string
      startedAt:
        type: string
      uptimeInHours:
        type: number
      uptimeInSec:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server to show the added swagger support.
  title: Server with healthcheck
  version: 0.0.1
paths:
  /healthcheck:
    get:
      description: Returns 200 OK up, if all's good.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthcheck endpoint
  /info:
    get:
      description: This is a current app's state endpoint, may be used for a diagnostic
        purpose.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.appInfo'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Information endpoint
swagger: "2.0"
